// Copyright 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package mpsns

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"strings"
)

const (
	// NamePrefix marks every namespace this package owns.
	//
	// It is what makes reconciliation safe to run against a live control
	// daemon: the sweep deletes namespaces that no live container claims, and
	// restricting it to names carrying this prefix means a namespace created by
	// anything else — a human debugging, a future feature, the daemon's own
	// `default` — is never a candidate, no matter how the list output is
	// parsed.
	NamePrefix = "kai_"

	// nameHashHex is how many hex characters of the container id's digest are
	// appended to every name. 20 hex characters is 80 bits: distinct container
	// ids collide with probability under 2^-40 even across the ~2^20 containers
	// a node might see in its lifetime, which is the property that matters —
	// two containers mapping to one namespace would silently share one compute
	// cap, and the one that released first would delete the other's namespace.
	nameHashHex = 20

	// nameSanitizedMax bounds the human-readable half of the name. It exists
	// only to keep the generated pipe directory short (see MaxPipeDirLength);
	// uniqueness comes entirely from the digest.
	nameSanitizedMax = 16

	// MaxPipeDirLength is the longest namespace pipe directory that can work.
	//
	// The directory holds a unix socket, and a unix socket path lives in
	// sockaddr_un.sun_path — 108 bytes INCLUDING the terminating NUL, so 107
	// usable characters, minus room for the socket's own basename. Measured on
	// driver 615: a 117-character pipe directory makes the control daemon fail
	// with a bare "Failed to initialize MPS control daemon" and write no log at
	// all. There is no diagnostic to work back from, which is precisely why
	// this is checked here and reported with the offending path.
	MaxPipeDirLength = unixPathMax - socketNameReserve

	// unixPathMax is sun_path's usable length: 108 bytes including the NUL.
	unixPathMax = 107

	// socketNameReserve is the room left inside the directory for the socket
	// basename the daemon creates there (`/control` is 8; the reserve is wide
	// enough that a longer name in a future driver does not turn into the
	// silent failure above).
	socketNameReserve = 24
)

// Name derives the MPS namespace name for a container id.
//
// Two constraints shape it, and both were measured rather than inferred:
//
//   - The control daemon accepts only [a-z0-9_]+ as a namespace name. No
//     uppercase and no hyphens. Kubernetes container and pod names routinely
//     contain hyphens and container ids are hex digests that may be presented
//     with any casing, so the input has to be mangled, and a mangling that is
//     not collision-free would let two containers share one cap.
//   - The name ends up inside a unix socket path with a hard length limit that
//     fails silently when exceeded (see MaxPipeDirLength), so it has to stay
//     short.
//
// The result is a fixed prefix, a sanitized and truncated slice of the id for
// human legibility in `namespace list`, and a digest of the WHOLE original id
// for uniqueness. Truncation and sanitization are both lossy; the digest is
// not, so two ids that sanitize or truncate to the same text still get
// different names.
//
// An empty id has no identity to preserve and is rejected rather than being
// given a name derived from nothing.
func Name(containerID string) (string, error) {
	if strings.TrimSpace(containerID) == "" {
		return "", fmt.Errorf("deriving an MPS namespace name: container id is empty")
	}

	digest := sha256.Sum256([]byte(containerID))
	name := NamePrefix + sanitize(containerID, nameSanitizedMax) + "_" + hex.EncodeToString(digest[:])[:nameHashHex]

	// Belt and braces: the pieces above are all drawn from [a-z0-9_] by
	// construction, so a failure here means one of them changed and the daemon
	// would have rejected the name with a message that names nothing useful.
	if !validName(name) {
		return "", fmt.Errorf("derived MPS namespace name %q for container %q is not [a-z0-9_]+", name, containerID)
	}
	return name, nil
}

// IsManagedName reports whether a namespace name was generated by Name, i.e.
// whether this package owns it. Reconciliation will not touch anything else.
func IsManagedName(name string) bool {
	return strings.HasPrefix(name, NamePrefix) && len(name) > len(NamePrefix) && validName(name)
}

// CheckPipeDirLength rejects a namespace pipe directory that is too long to
// hold a working control socket, naming the path and the limit.
//
// The check is explicit and eager because the failure it replaces is the worst
// kind: the daemon refuses to initialise, says only "Failed to initialize MPS
// control daemon", and logs nothing at all — no mention of a path, a length, or
// a socket.
func CheckPipeDirLength(dir string) error {
	if len(dir) > MaxPipeDirLength {
		return fmt.Errorf("MPS namespace pipe directory %q is %d characters, over the %d-character limit "+
			"(a unix socket path may not exceed %d bytes including its NUL, and the MPS control daemon fails to "+
			"initialise with no log at all when it does): shorten the MPS pipe directory",
			dir, len(dir), MaxPipeDirLength, unixPathMax+1)
	}
	return nil
}

// sanitize maps a string into [a-z0-9_], truncated to max characters. Every
// character outside the accepted set collapses to '_' rather than being
// dropped, so "a-b" and "a_b" stay distinct in the readable half; they would in
// any case be separated by the digest.
func sanitize(in string, max int) string {
	var b strings.Builder
	b.Grow(max)
	for _, r := range in {
		if b.Len() >= max {
			break
		}
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r - 'A' + 'a')
		default:
			b.WriteByte('_')
		}
	}
	return b.String()
}

// validName is the daemon's own acceptance rule, duplicated here so a name can
// be checked without a control daemon to ask.
func validName(name string) bool {
	if name == "" {
		return false
	}
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
		default:
			return false
		}
	}
	return true
}
